[profile.default]
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]